### ISSUE TITLE
need help connecting to database server. 

### ISSUE THREAD

**Issue by dgmdevelopment** [bitnami/bitnami-docker-mariadb#183] opened 2019-05-01 22:44 UTC
This is not a bug report, more a support question since I was told to ask here from bitnami forums. 
Can't seem to connect to the database server defined in a php script.  the server variable defined there is localhost or 127.0.0.1.  

1. run my docker-compose.yml file below using `docker-compose up -d`
```version: '2'

services:
  nginx:
    image: bitnami/nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./conf/nginx-vhost/myapp.conf:/opt/bitnami/nginx/conf/vhosts/myapp.conf
      - .:/app

  mariadb-master:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    volumes:
      - 'mariadb_master_data:/bitnami/mariadb'
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=<removed>
      - MARIADB_ROOT_PASSWORD=<removed>
      
  mariadb-slave:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=<removed>
      - MARIADB_USER=user
      - MARIADB_DATABASE=mydb
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=<removed>
      

  php-fpm:
    image: bitnami/php-fpm:5.6.40-debian-9-r99
    volumes:
      - .:/app

  phpmyadmin:
    image: 'bitnami/phpmyadmin:4'
    ports:
      - '8080:8081'
      - '443:443'
    depends_on:
      - mariadb-master
    volumes:
      - 'phpmyadmin_data:/bitnami'    
volumes:
  mariadb_master_data:
    driver: local
  phpmyadmin_data:
    driver: local
```

**Describe the results you received:**

Unable to connect to database server. 

**Describe the results you expected:**

Connection to mariadb server. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 8
 Running: 6
 Paused: 0
 Stopped: 2
Images: 8
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d210101
ID: JQJ7:YXA4:RSL3:KWKK:MZWQ:OGFQ:AQR2:ALNW:DSF5:EDBO:32BY:FBEO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 68
 Goroutines: 107
 System Time: 2019-05-01T22:36:06.8697265Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.0, build 0aa5906
docker-py version: 3.7.2
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Using Windows 10 - Windows Subsystem for Linux to connect to Docker daemon running on Docker for Windows.

**Comment by miguelaeh** [comment] 2019-05-02 07:07
Hi @dgmdevelopment,
If you set the database host to 127.0.0.1 I guess it won't work. That is because docker uses virtual networks behind the scenes. So, each container has a different IP (virtual) inside the docker network. I mean, PHP is not the same container as MariaDB while the 127.0.0.1 IP address is referencing the same container.
Using docker-compose you can connect the services between them using the service name. For instance, in your case you could set `mariadb-master` instead of `127.0.0.1` in the server variable and it should be translate to the IP address of the MariaDB master container.

**Comment by dgmdevelopment** [comment] 2019-05-02 16:19
Hello miguelaeh, thanks for the help. 
I understand your reply but not sure what I'm missing. Sorry, new to docker.  So does my docker compose file look correct or do i need to change something under the nginx area of it or php area? I tried entering the parameter in my php script (oscommerce) as 
`define('DB_SERVER', 'mariadb-master');`
and its still not seeing it.

**Comment by miguelaeh** [comment] 2019-05-03 11:22
> So does my docker compose file look correct or do i need to change something under the nginx area of it or php area?
I think yes, the docker-compose seem to be good. The Nginx depends on the config file you have mounted. In any case, php do not connect with MariaDB trough Nginx, it should be to manage request from the outside. 
Could you share you docker logs of the container?
I mean, you can run `docker ps` and it should appear some IDs. Take the php container ID and execute `docker logs <ID>`. It will show you some logs that could be useful.
I have try to reproduce your issue but I don't have your app for php, I mean, as you mounted some volumes with local paths I cannot reproduce your complete deployment.

**Comment by dgmdevelopment** [comment] 2019-05-04 21:21
I'm still struggling with the virtual hosts.  i checked logs but not show anything useful.  I think the issue appears with something to do with the paths used for the volumes. i am using Windows 10 with Ubuntu on the WSL (Windows subsystem for linux).  Could Bitnami perhaps add to their tutorial here: 
[https://docs.bitnami.com/containers/how-to/create-emp-environment-containers/](https://docs.bitnami.com/containers/how-to/create-emp-environment-containers/)
to get this working for people on win 10 and those using the WSL/Docker for windows.

**Comment by miguelaeh** [comment] 2019-05-06 10:17
Hi @dgmdevelopment ,
I will create an internal task to see if it is possible.

**Comment by dgmdevelopment** [comment] 2019-05-09 21:53
Hi @miguelaeh , 
I'm basically trying to get 4 separate bitnami containers (php, nginx, mariadb, and phpmyadmin) networked as my dev environment.  Ideally with virtual hosts setup on it properly.  Again this is local dev, not production.   
Basically what i need is a docker-compose file that makes it all happen.  The tutorial referenced didn't work for me.  I'm interested in the non-root containers Bitnami provides for security reasons. 
Thanks!

**Comment by miguelaeh** [comment] 2019-05-10 07:03
Hi @dgmdevelopment ,
Our MariaDB and Nginx containers are non-root for all platforms, but php and phpmyadmin aren't non-root containers for debian nor oracle (they are for rhel).
>The tutorial referenced didn't work for me.

I am not sure about why it didn't work for you. If you use WSL, commands should be the same as Linux. Also, Docker run in Windows too by default. Could you paste here the errors?

**Comment by dgmdevelopment** [comment] 2019-05-11 00:54
Sorry it took me some time to revisit this. In reworking things, the only issue
I have is with the mariadb container. It's just a permissions issue. Since you
said this is a non root container, what do i need to change in the docker
compose file.  
```INFO  ==> ** Starting MariaDB setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
INFO  ==> Initializing mariadb database...
mkdir: cannot create directory '/bitnami/mariadb': Permission denied
INFO  ==> Stopping mariadb...
```

One other note: when using the latest nginx container, the path has changed
using the server-blocks folder so the tutorial would need updating to reflect
this. `- ./nginx-vhost/myapp.conf:/bitnami/nginx/conf/server-blocks/myapp.conf`

My docker-compose is:
```version: '2'

services:
  nginx:
    image: bitnami/nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx-vhost/myapp.conf:/bitnami/nginx/conf/server-blocks/myapp.conf
      - .:/app

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=cb37trwso*
    volumes:
      - ./mariadb-data:/bitnami

  php-fpm:
    image: bitnami/php-fpm:latest
    volumes:
      - .:/app```

**Comment by miguelaeh** [comment] 2019-05-13 06:36
Hi @dgmdevelopment ,
Nice to know you solved it. 
I will close this issue. Feel free to open it again if you need help.

**Closed** 2019-05-13 06:36 UTC

**Comment by hAh0L13** [comment] 2020-06-17 04:39
Can I reopen this issue?
My problem with latest update on `10.2` images when using with OKD\OpenShift:  
```oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

Server https://[removed]:443
openshift v3.10.45
kubernetes v1.10.0+b81c8f8
```
MariaDB installed through Helm2 from bitnami chart [6.4.2](https://github.com/bitnami/charts/tree/master/bitnami/mariadb) long time ago. I cannot connect to DB from another pod in namespace/cluster, because exec string for mysqld contain `--bind-address 127.0.0.1`
I try to setup environment for statefulSet **DB_BIND_ADDRESS** and **MARIADB_BIND_ADDRESS** to the field `status.podIP`, so it always receive actual pod virtual IP.
But in logs i see
`mariadb 09:51:33.73 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.`  
I think this warn suppress given *_BIND_ADDRESS options so 127.0.0.1 remains in exec string. File **my.cnf** mounted to pod from configMap - as templated in chart, but since K8s 1.9.6 configMap/Secrets/DownwardAPI/etc volumes are [read-only](https://github.com/kubernetes/kubernetes/issues/62099) and volumeMounts option `readOnly: false` being ignored. 
Placing `bind-address=0.0.0.0` in my.cnf configMap in mysqld section didn't help me.  
How should I configure statefulSet/configMap or other resource for correct work with DB from another pod's? Now I temporary rolled back statefulSet to **10.2.32-debian-10-r17**

**Comment by miguelaeh** [comment] 2020-06-17 08:11
Hi @hAh0L13 ,
How are you trying to connect to MariaDB? The Pod IP is not static, so it should not be used in the configuration. To connect to MariaDB pods you should use the service name as the hostname. Are you using it in that way?

**Comment by hAh0L13** [comment] 2020-06-17 08:48
> To connect to MariaDB pods you should use the service name

Yes, I'm using service name. But on actual **10.2** image I receive `connection refused` when try connection from another pod. With old image **10.2.32-debian-10-r17** connection success.
I found changes in exec string - actual images adding `--bind-address 127.0.0.1` flag (in [libmariadb.sh](https://github.com/bitnami/bitnami-docker-mariadb/blob/7ae5624dca6e5f0afab9e53c51fbe47eb42052c7/10.2/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh#L555) I think) and didn't delete this flag. I cannot find why and what should I do next

**Comment by miguelaeh** [comment] 2020-06-18 10:01
Hi @hAh0L13 ,
Could you test the same scenario using the env var `BITNAMI_DEGUB=1` and share the logs?

**Comment by hAh0L13** [comment] 2020-06-19 04:38
Adding `BITNAMI_DEBUG=true`
```

  | mariadb 04:23:17.65
  | mariadb 04:23:17.66 Welcome to the Bitnami mariadb container
  | mariadb 04:23:17.66 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
  | mariadb 04:23:17.66 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
  | mariadb 04:23:17.66
  | mariadb 04:23:17.66 INFO  ==> ** Starting MariaDB setup **
  | mariadb 04:23:17.68 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
  | mariadb 04:23:17.69 INFO  ==> Initializing mariadb database
  | mariadb 04:23:17.70 DEBUG ==> Ensuring expected directories/files exist
  | mariadb 04:23:17.72 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
  | mariadb 04:23:17.72 INFO  ==> Using persisted data
  | mariadb 04:23:17.75 INFO  ==> Running mysql_upgrade
  | mariadb 04:23:17.76 INFO  ==> Starting mariadb in background
  | 2020-06-19  4:23:17 139999717627712 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.2.32-MariaDB-log) starting as process 54 ...
  | 2020-06-19  4:23:17 139999717627712 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
  | 2020-06-19  4:23:17 139999717627712 [Note] InnoDB: Uses event mutexes
  | 2020-06-19  4:23:17 139999717627712 [Note] InnoDB: Compressed tables use zlib 1.2.11
  | 2020-06-19  4:23:17 139999717627712 [Note] InnoDB: Using Linux native AIO
  | 2020-06-19  4:23:17 139999717627712 [Note] InnoDB: Number of pools: 1
  | 2020-06-19  4:23:17 139999717627712 [Note] InnoDB: Using SSE2 crc32 instructions
  | 2020-06-19  4:23:17 139999717627712 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
  | 2020-06-19  4:23:17 139999717627712 [Note] InnoDB: Completed initialization of buffer pool
  | 2020-06-19  4:23:17 139999237256960 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
  | 2020-06-19  4:23:17 139999717627712 [Note] InnoDB: Highest supported file format is Barracuda.
  | 2020-06-19  4:23:17 139999717627712 [Note] InnoDB: Starting crash recovery from checkpoint LSN=178452118
  | 2020-06-19  4:23:18 139999717627712 [Note] InnoDB: Last binlog file './mysql-bin.000015', position 227810
  | 2020-06-19  4:23:20 139999717627712 [Note] InnoDB: 128 out of 128 rollback segments are active.
  | 2020-06-19  4:23:20 139999717627712 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
  | 2020-06-19  4:23:20 139999717627712 [Note] InnoDB: Creating shared tablespace for temporary tables
  | 2020-06-19  4:23:20 139999717627712 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
  | 2020-06-19  4:23:20 139999717627712 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
  | 2020-06-19  4:23:20 139999717627712 [Note] InnoDB: Waiting for purge to start
  | 2020-06-19  4:23:20 139999717627712 [Note] InnoDB: 5.7.30 started; log sequence number 178452127
  | 2020-06-19  4:23:20 139998997235456 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
  | 2020-06-19  4:23:20 139998997235456 [Note] InnoDB: Buffer pool(s) load completed at 200619  4:23:20
  | 2020-06-19  4:23:20 139999717627712 [Note] Plugin 'FEEDBACK' is disabled.
  | 2020-06-19  4:23:20 139999717627712 [Note] Recovering after a crash using mysql-bin
  | 2020-06-19  4:23:20 139999717627712 [Note] Starting crash recovery...
  | 2020-06-19  4:23:20 139999717627712 [Note] Crash recovery finished.
  | 2020-06-19  4:23:20 139999717627712 [Note] Server socket created on IP: '127.0.0.1'.
  | 2020-06-19  4:23:20 139999717627712 [Warning] 'proxies_priv' entry '@% root@icc-mariadb-0' ignored in --skip-name-resolve mode.
  | 2020-06-19  4:23:20 139999717627712 [Note] Reading of all Master_info entries succeeded
  | 2020-06-19  4:23:20 139999717627712 [Note] Added new Master_info '' to hash table
  | 2020-06-19  4:23:20 139999717627712 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
  | Version: '10.2.32-MariaDB-log'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
```
From another pod - 
```
$ curl icc-mariadb.icckb-2.svc:3306 --noproxy '*'
curl: (7) Failed to connect to icc-mariadb.icckb-2.svc port 3306: Connection refused
$ curl icc-mariadb-slave.icckb-2.svc:3306 --noproxy '*'
curl: (1) Received HTTP/0.9 when not allowed
```
Slave replica with same scenario (update to actual 10.2) didn't stop at 
```
  | 2020-06-19  4:19:52 140278611801920 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
  | Version: '10.2.32-MariaDB-log'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
```
And continue init/starting process and at the end server socket changes from 127.0.0.1 -> 0.0.0.0

**Comment by miguelaeh** [comment] 2020-06-19 08:33
Hi @hAh0L13 ,
Try to remove the `--noproxy` option from the `curl` command:
```
I have no name!@maria-mariadb-slave-0:/$ curl maria-mariadb:3306
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
I have no name!@maria-mariadb-slave-0:/$ curl maria-mariadb:3306 --no-proxy '*'
curl: (7) Failed to connect to * port 1080: Connection refused
I have no name!@maria-mariadb-slave-0:/$
```

**Comment by hAh0L13** [comment] 2020-06-22 06:13
I'm using `noproxy` option because without it, request wil go outside cluster. Testing with `mysql` command or `mysqli` php connector shows similar result: successfull connection to slave replica and connection refused to master replica.  
I really think my problem is that master replica stop after background start - [with `bind-address 127.0.0.1` option](https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.2/debian-10/rootfs/opt/bitnami/scripts/libmariadb.sh#L561)

**Comment by miguelaeh** [comment] 2020-06-22 07:22
Hi @hAh0L13 ,
If the master stops, Kubernetes will try to restart the Pod so you should see a high number of restarts in that pod when executing `kubectl get pods`.

> MariaDB installed through Helm2 from bitnami chart 6.4.2 long time ago
Is it possible in your case to install the Helm chart again, so we can check if it is a problem in the upgrade from the old one?

**Comment by hAh0L13** [comment] 2020-06-22 07:41
> If the master stops

I mean that master works, but keeps in "background state". As described in `libmariadb.sh`, this state allowing only local connections, waited full initialization of DB

**Comment by miguelaeh** [comment] 2020-06-23 16:48
Do you know how could I replicate this? I am not able to reproduce the issue. Did you perform any customizations?

**Comment by menih** [comment] 2020-07-21 05:54
I see the same issue. Is there a workaround?

**Comment by marcosbc** [comment] 2020-07-22 17:37
@menih It looks like this issue has been closed for some time. Could you open a new issue and provide as much information as possible related to your specific error? And if possible, please provide some steps to reproduce this issue.

**Comment by menih** [comment] 2020-07-22 17:42
I think the issue fixed itself... after few retries, it worked.
