### ISSUE TITLE
Need your help

### ISSUE THREAD

**Issue by beautyonly** [bitnami/bitnami-docker-mariadb#145] opened 2018-05-30 10:23 UTC
HI Hello

I am very happy to have access to your wordpress docker container and I am very honored to be able to use it

But I have a few questions if your side can help me

1. the theme I can specify in the `directory/4/Dockerfile` configuration document using my pre-made templates and plug-ins.

2. Can I configure the TDK information for the site in the `/4/Dockerfile/configuration` file? Such as: keywords, description, etc.

3. I can configure the corresponding field in the /4/Dockerfile configuration and configure
Corresponding TDK information, such as: keywords, description

4/ using your docker container can support the establishment of a large number of sites

thank

**Comment by juan131** [comment] 2018-05-31 07:57
Hi @beautyonly 

These questions related to WordPress, aren't they? I proceed to close the issue since it's not related with this Docker Image and it's a duplicate of https://github.com/bitnami/bitnami-docker-wordpress/issues/134

**Closed by juan131** 2018-05-31 07:57 UTC
