### ISSUE TITLE
can't rmdir './test', errno: 39 "Directory not empty"

### ISSUE THREAD

**Issue by fcxjluo** [bitnami/bitnami-docker-mariadb#92] opened 2016-11-29 11:30 UTC
When I create container,the error happened.
```
nami    INFO  Initializing mariadb
mariadb INFO  ==> Creating database my_database...
mariadb INFO  ==> Creating user my_user...
mariadb INFO  ==> Granting access to my_user to the database my_database...
mariadb INFO  ==> Creating 'root' user with unrestricted access...
Error executing 'postInstallation': ERROR 1010 (HY000) at line 1: Error dropping database (can't rmdir './test', errno: 39 "Directory not empty")
```

**Comment by sameersbn** [comment] 2016-11-30 05:57
@fcxjluo Can you make sure the host directory mounted at `/bitnami/mariadb` path of the container is empty before launching the container? 

If the issue persists could you please provide some details about your environment and the docker command or docker-compose.yml file you used. It could help us reproduce the issue and suggest a resolution.

The following information is useful for tracking down possible issues:
 - Host OS info (`uname -a`)
 - If using `Docker for Mac` or `Docker for Windows`, `Boot2Docker`, etc.
 - Output of `docker info`
 - `bitnami/mariadb` image version used
 - docker command or docker-compose.yml file

**Comment by sameersbn** [comment] 2016-11-30 08:23
I was able to reproduce this issue on a CentOS 7.2 host using the `overlay` storage driver. We have noticed issues with basic filesystem operations in docker when the overlay storage driver is in use and therefore suggest switching to a more mature storage driver.

It is likely that your docker host machine is using the overlay driver as well. There isn't a resolution that we can provide as the issue is caused at the file system level.

**Comment by fcxjluo** [comment] 2016-11-30 08:33
Hi，sameersbn.Yes,I used the overlay storage driver,and the reason of the issue is the volume is not empty.But,I ran the container without “-v” option,and it's the first time to run,so I'm confusied.Thanks.

**Comment by sameersbn** [comment] 2016-11-30 08:55
@fcxjluo the issue is with the use of the overlay driver, please switch to using devicemapper storage driver if you are using RHEL/CentOS

**Comment by juan131** [comment] 2017-02-17 10:06
@fcxjluo can you confirm that using devicemapper storage driver fix the issue? I think we can close this issue since the error doesn't seem to be related with the Docker Image.

**Comment by sameersbn** [comment] 2017-02-24 11:04
**Update:**

RHEL treats OverlayFS as a preview filesystem. The following document https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html lists the problems and possible workarounds for using OverlayFS with Docker on RHEL 7.2. 

We hope you find the information contained in this referenced document useful.

**Comment by sameersbn** [comment] 2017-02-24 11:04
marking the issue as resolved.

**Closed by sameersbn** 2017-02-24 11:04 UTC
